[project]
name = "pyvcontrol"
version = "0.1.0"
description = "Communication with Viessmann heating via Optolink interface."
readme = "README.md"
authors = [
    { name = "Jochen SchmÃ¤hling", email = "js1157@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "deprecated>=1.3.1",
    "pyserial>=3.5",
    "pyyaml>=6.0.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
